project:
  type: website
  output-dir: docs

website:
  title: "GeoData"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: 
      light: lux
      dark: slate
    css: styles.css
editor: visual